import type { Listing, Review, User, Conversation, Message } from './types';

// Mock current user
export const mockUser: User = {
  id: 'user-1',
  name: 'Miles Morales',
  email: 'miles.morales@ucla.edu',
  verifiedUCLA: true,
  bookmarks: [],
};

// Mock listings with UCLA-area addresses
export const mockListings: Listing[] = [
  {
    id: 'listing-1',
    title: 'Sunny single in 3BR Westwood apartment',
    price: 1650,
    address: '691 Levering Ave',
    distanceFromCampus: 0.5,
    images: [
      '/listings/apt4_3.jpg',
      '/listings/apt1_2.webp',
      '/listings/apt1_3.webp',
    ],
    roomType: 'single',
    bathroomType: 'shared',
    moveInDate: '2026-06-10',
    moveOutDate: '2026-08-10',
    quarter: ['summer'],
    roommatePreference: 'male',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'covered',
      fitnessCenter: true,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Looking for a clean and responsible student to take over my single room for the summer. The apartment is shared with two other chill guys (both juniors). Great natural lighting, comes fully furnished with a desk and chair. All utilities included in the rent price!',
    listerId: 'user-5',
    createdAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'listing-2',
    title: 'Spacious 1BR with private bath on Wilshire Blvd',
    price: 2200,
    address: '10889 Wilshire Blvd',
    distanceFromCampus: 0.8,
    images: [
      '/listings/apt6.jpg',
      '/listings/apt2_2.webp',
    ],
    roomType: 'single',
    bathroomType: 'private',
    moveInDate: '2026-09-15',
    moveOutDate: '2026-12-15',
    quarter: ['fall'],
    roommatePreference: 'coed',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: true,
      laundryInUnit: true,
      laundryOnSite: false,
      balcony: true,
      parking: 'garage',
      fitnessCenter: true,
      pool: true,
      hotTub: true,
      accessible: true,
    },
    description: 'Modern studio in a luxury building. Perfect for grad students or upperclassmen. Walking distance to campus with amazing amenities.',
    listerId: 'user-6',
    createdAt: '2026-02-09T14:30:00Z',
  },
  {
    id: 'listing-3',
    title: 'Double room in modern 2BR near Roebling',
    price: 950,
    address: '10982 Roebling Ave',
    distanceFromCampus: 0.4,
    images: [
      '/listings/apt3_1.jpg',
      '/listings/apt3_3.jpg',
    ],
    roomType: 'double',
    bathroomType: 'shared',
    moveInDate: '2026-06-20',
    moveOutDate: '2026-09-20',
    quarter: ['summer', 'fall'],
    roommatePreference: 'female',
    verifiedUCLA: false,
    amenities: {
      furnished: false,
      internet: true,
      ac: false,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'covered',
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Affordable double room perfect for two friends! Close to campus, quiet building, great landlord.',
    listerId: 'user-7',
    createdAt: '2026-02-08T09:15:00Z',
  },
  {
    id: 'listing-4',
    title: 'Large single with ensuite bath, 3 min to campus',
    price: 1850,
    address: '565 Gayley Ave',
    distanceFromCampus: 0.3,
    images: [
      '/listings/apt4_1.jpg',
      '/listings/apt4_2.jpg',
    ],
    roomType: 'single',
    bathroomType: 'private',
    moveInDate: '2026-04-01',
    moveOutDate: '2026-06-30',
    quarter: ['spring'],
    roommatePreference: 'coed',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: true,
      laundryInUnit: true,
      laundryOnSite: false,
      balcony: true,
      parking: 'covered',
      fitnessCenter: true,
      pool: true,
      hotTub: false,
      accessible: false,
    },
    description: 'Spacious single bedroom with ensuite bathroom. Recently renovated with modern finishes. 2-minute walk to campus!',
    listerId: 'user-8',
    createdAt: '2026-02-07T16:45:00Z',
  },
  {
    id: 'listing-5',
    title: 'Single room in 4BR house on Landfair Ave',
    price: 1400,
    address: '523 Landfair Ave',
    distanceFromCampus: 0.6,
    images: [
      '/listings/apt5.jpg',
    ],
    roomType: 'single',
    bathroomType: 'shared',
    moveInDate: '2026-06-15',
    moveOutDate: '2026-08-31',
    quarter: ['summer'],
    roommatePreference: 'coed',
    verifiedUCLA: false,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: null,
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Fun summer sublease with 3 awesome roommates who love to cook and hang out! Chill vibe, close to campus.',
    listerId: 'user-9',
    createdAt: '2026-02-06T11:20:00Z',
  },
  {
    id: 'listing-6',
    title: 'Budget-friendly triple on Strathmore Dr, all utils included',
    price: 750,
    address: '10850 Strathmore Dr',
    distanceFromCampus: 1.2,
    images: [
      '/listings/apt3_2.jpg',
    ],
    roomType: 'triple+',
    bathroomType: 'shared',
    moveInDate: '2026-06-24',
    moveOutDate: '2026-09-01',
    quarter: ['summer'],
    roommatePreference: 'male',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: false,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'garage',
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Subletting my spot in a triple for the summer — it\'s a solid room and honestly one of the better deals you\'ll find this close to campus. The three of us have been living here since fall and the place has a really comfortable vibe. Kitchen is fully stocked, fridge and microwave are there, and we keep it pretty clean. Garage parking is included which is rare at this price point. Laundry is on-site in the building. The walk to campus is about 15 minutes which sounds like a lot but you get used to it fast — especially when you\'re saving this much on rent. All utilities are split and baked into the price so no surprise bills. Looking for someone easygoing who\'s okay with a shared bathroom situation. We\'re around most evenings but everyone does their own thing. Good fit if you\'re here for a summer internship or just want a low-key place to land.',
    listerId: 'user-10',
    createdAt: '2026-02-05T13:00:00Z',
  },
  {
    id: 'listing-7',
    title: 'Luxury furnished 1BR with city views · Wilshire',
    price: 2500,
    address: '10990 Wilshire Blvd',
    distanceFromCampus: 0.9,
    images: [
      '/listings/apt7_1.jpg',
      '/listings/apt7_2.png',
    ],
    roomType: 'single',
    bathroomType: 'private',
    moveInDate: '2026-07-01',
    moveOutDate: '2026-09-30',
    quarter: ['summer', 'fall'],
    roommatePreference: 'coed',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: true,
      laundryInUnit: true,
      laundryOnSite: false,
      balcony: true,
      parking: 'garage',
      fitnessCenter: true,
      pool: true,
      hotTub: true,
      accessible: true,
    },
    description: 'High-end 1-bedroom apartment with floor-to-ceiling windows and stunning city views. Perfect for summer internship.',
    listerId: 'user-11',
    createdAt: '2026-02-04T08:30:00Z',
  },
  {
    id: 'listing-8',
    title: 'Female roommate wanted, 2BR on Landfair Ave',
    price: 1300,
    address: '636 Landfair Ave',
    distanceFromCampus: 0.5,
    images: [
      '/listings/apt8_1.jpg',
      '/listings/apt8_2.jpg',
    ],
    roomType: 'single',
    bathroomType: 'shared',
    moveInDate: '2026-01-05',
    moveOutDate: '2026-03-20',
    quarter: ['winter'],
    roommatePreference: 'female',
    verifiedUCLA: true,
    amenities: {
      furnished: true,
      internet: true,
      ac: true,
      fridge: true,
      microwave: true,
      dishwasher: false,
      laundryInUnit: false,
      laundryOnSite: true,
      balcony: false,
      parking: 'street',
      fitnessCenter: false,
      pool: false,
      hotTub: false,
      accessible: false,
    },
    description: 'Looking for a female roommate for winter quarter. We\'re all bio majors and super friendly!',
    listerId: 'user-12',
    createdAt: '2026-02-03T15:45:00Z',
  },
];

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    listingId: 'listing-1',
    source: 'reddit',
    sourceUrl: 'https://reddit.com/r/ucla/comments/example1',
    sourceName: 'r/ucla',
    text: 'Levering Ave is usually pretty quiet but gets busy during finals. This building has great management and they fix things quickly.',
    timestamp: '2025-12-15T10:00:00Z',
  },
  {
    id: 'review-2',
    listingId: 'listing-1',
    source: 'bruinwalk',
    sourceUrl: 'https://bruinwalk.com/apartments/example1',
    sourceName: 'Bruinwalk Apartments',
    text: 'Walking distance to south campus is unbeatable. Units are slightly older but well maintained.',
    timestamp: '2025-08-20T14:30:00Z',
  },
  {
    id: 'review-3',
    listingId: 'listing-4',
    source: 'reddit',
    sourceUrl: 'https://reddit.com/r/ucla/comments/example2',
    sourceName: 'r/ucla',
    text: 'Gayley is super close to everything. Literally wake up 10 minutes before class and still make it on time. Parking is tough though.',
    timestamp: '2025-11-05T09:15:00Z',
  },
  {
    id: 'review-4',
    listingId: 'listing-4',
    source: 'bruinwalk',
    sourceUrl: 'https://bruinwalk.com/apartments/example2',
    sourceName: 'Bruinwalk Apartments',
    text: 'One of the best locations in Westwood. Building is clean and secure. Would definitely recommend!',
    timestamp: '2025-10-10T16:00:00Z',
  },
  {
    id: 'review-5',
    listingId: 'listing-7',
    source: 'reddit',
    sourceUrl: 'https://reddit.com/r/ucla/comments/example3',
    sourceName: 'r/ucla',
    text: 'Wilshire corridor has amazing buildings but they\'re pricey. Worth it if you can afford it - gym and pool are top-notch.',
    timestamp: '2025-09-25T11:30:00Z',
  },
  {
    id: 'review-3a',
    listingId: 'listing-3',
    source: 'reddit',
    sourceUrl: 'https://www.reddit.com/r/ucla/comments/1qgks4x/club_california_on_roebling_apartment_thoughts/',
    sourceName: 'r/ucla',
    text: 'It\'s pricey but nice. The gym facilities, pool, lounge and I think they still have the half basketball court, are all really nice. I lived there during undergrad back in 2015-2017 and I really liked it. I never had any issues with noise. At the time a lot of med students/residents lived there.',
    timestamp: '2025-12-01T10:00:00Z',
  },
  {
    id: 'review-3b',
    listingId: 'listing-3',
    source: 'bruinwalk',
    sourceUrl: 'https://bruinwalk.com/apartments/10982-roebling-ave/',
    sourceName: 'Bruinwalk',
    text: 'Surprisingly rude management. Do NOT expect to have a social atmosphere — parties are NOT tolerated.',
    timestamp: '2026-03-03T10:00:00Z',
  },
  {
    id: 'review-6a',
    listingId: 'listing-6',
    source: 'reddit',
    sourceUrl: 'https://reddit.com/r/ucla',
    sourceName: 'r/ucla',
    text: 'Lived on Strathmore last summer and honestly loved it. Super chill block, pretty quiet compared to the Westwood Village side. The buildings are older but the landlords on that stretch are generally responsive. Good spot if you want to save money and don\'t mind the slightly longer walk to campus.',
    timestamp: '2025-11-18T14:00:00Z',
  },
  {
    id: 'review-6c',
    listingId: 'listing-6',
    source: 'bruinwalk',
    sourceUrl: 'https://bruinwalk.com/apartments/',
    sourceName: 'Bruinwalk',
    text: 'Decent budget option for students. Units are spacious for the price point and the neighborhood is safe. Street noise can be an issue on weekends but nothing unreasonable. Management was easy to reach when we had a maintenance issue.',
    timestamp: '2025-09-10T11:00:00Z',
  },
  {
    id: 'review-3c',
    listingId: 'listing-3',
    source: 'yelp',
    sourceUrl: 'https://www.yelp.com/biz/club-california-apartments-los-angeles',
    sourceName: 'Yelp',
    text: 'Absolutely horrible apartment building. Living here is only marginally better than being homeless. There are multiple frat houses directly underneath and around the building blaring loud music until the wee hours of the morning. Management is practically absent and non responsive to maintenance calls. Streets around it are filthy and filled with people experiencing homelessness. There are tons of package thefts and vehicular breakins. I did not feel safe here. Rents here are usually too high considering the downsides — tread carefully.',
    timestamp: '2025-06-15T10:00:00Z',
  },
];

// Mock messages and conversations — populated live via compose modal
export const mockMessages: Message[] = [];

export const mockConversations: Conversation[] = [];
